### PR TITLE
W-17239370: fix flaky test

### PR DESCRIPTION
**Pull request by rbourbonnavarro**
(cherry picked from commit e3baa4d8b5f3d9e6c60ba8f6e6cbd813a9c93b04)

### CODE REVIEW

**Review by mbuchwald — APPROVED** [review]

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Review by mbuchwald — DISMISSED** [review]

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Review by mbuchwald — APPROVED** [review]

**Pull request merged**
