### PR TITLE
W-13214671: Fix DistributedOpenTelemetryTracingTestCase flaky test

### PR DESCRIPTION
**Pull request by IvanAndresFritzler**

### CODE REVIEW

**Review by fsgonz — APPROVED** [review]

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Pull request merged**
