### PR TITLE
Fix test due to db connector snapshot update (#1920)

### PR DESCRIPTION
**Pull request by rbourbonnavarro**
(cherry picked from commit f53c84b15b245223a39ecaba0dc7ed0b03d3e4c4)

### CODE REVIEW

**Review by elrodro83 — APPROVED** [review]

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Pull request merged**
