### PR TITLE
W-12967336: Fix tests due to fixing split packages between mure-core and mule-core-components

### PR DESCRIPTION
**Pull request by mule-pachanady**
This is due to https://github.com/mulesoft/mule/pull/12364

### CODE REVIEW

**Review by fsgonz — APPROVED** [review]

**Comment by mule-pachanady** [comment]
--validate

**Comment by mule-pachanady** [comment]
@fsgonz Need review due to rebase Thanks

**Comment by mule-pachanady** [comment]
--validate

**Comment by mule-pachanady** [comment]
--validate

**Pull request merged**
